# Generated by Django 6.0.1 on 2026-02-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('police', 'Police Station'), ('hospital', 'Hospital'), ('ambulance', 'Ambulance Service'), ('fire', 'Fire Station'), ('roadside', 'Roadside Assistance')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_24x7', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Emergency Services',
                'ordering': ['service_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='Starting location', max_length=255)),
                ('destination', models.CharField(help_text='Destination location', max_length=255)),
                ('origin_lat', models.FloatField(default=0.0)),
                ('origin_lng', models.FloatField(default=0.0)),
                ('dest_lat', models.FloatField(default=0.0)),
                ('dest_lng', models.FloatField(default=0.0)),
                ('distance_km', models.FloatField(help_text='Distance in kilometers')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car')], max_length=20)),
                ('fuel_cost', models.FloatField(help_text='Estimated fuel cost in INR')),
                ('fuel_liters', models.FloatField(default=0.0, help_text='Fuel required in liters')),
                ('stops_visited', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vendor_type', models.CharField(choices=[('food', 'Food & Restaurant'), ('hotel', 'Hotel & Lodge'), ('workshop', 'Puncture & Workshop')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField(default=4.0)),
                ('phone', models.CharField(max_length=15)),
                ('image_url', models.URLField(blank=True)),
                ('is_open', models.BooleanField(default=True)),
                ('price_range', models.CharField(default='₹₹', help_text='Price range indicator', max_length=10)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
