# Generated by Django 6.0.1 on 2026-02-05 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='availability_status',
            field=models.CharField(default='Available', help_text='Status for workshops (Available/Busy)', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base price for room or service', max_digits=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rooms_available',
            field=models.IntegerField(default=0, help_text='Number of rooms available (for hotels)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct'), ('goibibo', 'Goibibo'), ('mmt', 'MakeMyTrip'), ('yatra', 'Yatra'), ('booking', 'Booking.com')], default='direct', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='timing',
            field=models.CharField(default='9:00 AM - 9:00 PM', help_text='Opening and closing hours', max_length=100),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core_api.vendor')),
            ],
        ),
    ]
